export const species = {
  'bronze-winged-jacana': { name: 'Bronze-winged Jacana' },
  'indian-cormorant': { name: 'Indian Cormorant' },
  'indian-pond-heron': { name: 'Indian Pond-Heron' },
  'little-egret': { name: 'Little Egret' },
  'oriental-darter': { name: 'Oriental Darter' },
  'purple-heron': { name: 'Purple Heron' },
  'white-throated-kingfisher': { name: 'White-throated Kingfisher' },
  'pied-bushchat': { name: 'Pied Bushchat' },
  'asian-koel': { name: 'Asian Koel' },
  'asian-tit': { name: 'Asian Tit' },
  'black-kite': { name: 'Black Kite' },
  'blue-faced-malkoha': { name: 'Blue-faced Malkoha' },
  'common-iora': { name: 'Common Iora' },
  'indian-paradise-flycatcher': { name: 'Indian Paradise-Flycatcher' },
  'laughing-dove': { name: 'Laughing Dove' },
  'pale-billed-flowerpecker': { name: 'Pale-billed Flowerpecker' },
  'yellow-billed-babbler': { name: 'Yellow-billed Babbler' },
  'ashy-prinia': { name: 'Ashy Prinia' },
  'asian-green-bee-eater': { name: 'Asian Green Bee-Eater' },
  'common-myna': { name: 'Common Myna' },
  'coppersmith-barbet': { name: 'Coppersmith Barbet' },
  'greater-coucal': { name: 'Greater Coucal' },
  'indian-peafowl': { name: 'Indian Peafowl' },
  'little-grebe': { name: 'Little Grebe' },
  'rose-ringed-parakeet': { name: 'Rose-ringed Parakeet' },
  'tickells-blue-flycatcher': { name: "Tickell's Blue Flycatcher" },
  'white-browed-wagtail': { name: 'White-browed Wagtail' },
  'white-cheeked-barbet': { name: 'White-cheeked Barbet' },
  'black-drongo': { name: 'Black Drongo' },
  'brahminy-kite': { name: 'Brahminy Kite' },
  'gray-heron': { name: 'Gray Heron' },
  'great-cormorant': { name: 'Great Cormorant' },
  'indian-spot-billed-duck': { name: 'Indian Spot-billed Duck' },
  'indian-white-eye': { name: 'Indian White-eye' },
  'jungle-myna': { name: 'Jungle Myna' },
  'medium-egret': { name: 'Medium Egret' },
  'purple-rumped-sunbird': { name: 'Purple-rumped Sunbird' },
  'red-vented-bulbul': { name: 'Red-vented Bulbul' },
  'red-whiskered-bulbul': { name: 'Red-whiskered Bulbul' },
  'scaly-breasted-munia': { name: 'Scaly-breasted Munia' },
  'spot-billed-pelican': { name: 'Spot-billed Pelican' },
  'spotted-dove': { name: 'Spotted Dove' },
  'white-breasted-waterhen': { name: 'White-breasted Waterhen' },
  'common-tailorbird': { name: 'Common Tailorbird' },
  'glossy-ibis': { name: 'Glossy Ibis' },
  'gray-wagtail': { name: 'Gray Wagtail' },
  'painted-stork': { name: 'Painted Stork' },
  'purple-sunbird': { name: 'Purple Sunbird' }
} satisfies Record<string, { name: string }>;
